[package]
name = "starknet_forge_template"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.1.0-rc2"

[tool.snforge]
# exit_first = true

[tool.sncast.myprofile]
account = "user"
network = "testnet"
url = "http://127.0.0.1:5050/rpc"

